name: Build Unity Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Unity
        uses: game-ci/unity-builder@v2 
        with:
          unityVersion: '2022.3.12f1'
          
      - name: Set Unity License
         env:
           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Build Unity Project
        run: |   
          ./path/to/Unity -batchmode -nographics -silent-crashes -logFile \
          -projectPath $(pwd) -buildTarget StandaloneWindows64 \
          -quit outputPath/mygame.exe  

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Unity-Build
          path: outputPath/ 
