name: Build Unity Game

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master 

      - name: Activate Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: echo $UNITY_LICENSE | tr -d '\r' | unity-setup activate-license 

      - name: Build Unity Game
        uses: game-ci/unity-builder@v2
        env:
          UNITY_VERSION: 2022.3.12f1
        with:
          buildName: ExamenBuild 

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyGameBuild
          path: build/ 
